/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcrobaticsRouteImport } from './routes/acrobatics'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DanceRouteImport } from './routes/dance'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MusicRouteImport } from './routes/music'
import { Route as PaintingsRouteImport } from './routes/paintings'
import { Route as SculptingRouteImport } from './routes/sculpting'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SubscriptionRouteImport } from './routes/subscription'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcrobaticsRoute = AcrobaticsRouteImport.update({
  id: '/acrobatics',
  path: '/acrobatics',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DanceRoute = DanceRouteImport.update({
  id: '/dance',
  path: '/dance',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const PaintingsRoute = PaintingsRouteImport.update({
  id: '/paintings',
  path: '/paintings',
  getParentRoute: () => rootRouteImport,
} as any)
const SculptingRoute = SculptingRouteImport.update({
  id: '/sculpting',
  path: '/sculpting',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acrobatics': typeof AcrobaticsRoute
  '/contact': typeof ContactRoute
  '/dance': typeof DanceRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/music': typeof MusicRoute
  '/paintings': typeof PaintingsRoute
  '/sculpting': typeof SculptingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/subscription': typeof SubscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acrobatics': typeof AcrobaticsRoute
  '/contact': typeof ContactRoute
  '/dance': typeof DanceRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/music': typeof MusicRoute
  '/paintings': typeof PaintingsRoute
  '/sculpting': typeof SculptingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/subscription': typeof SubscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acrobatics': typeof AcrobaticsRoute
  '/contact': typeof ContactRoute
  '/dance': typeof DanceRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/music': typeof MusicRoute
  '/paintings': typeof PaintingsRoute
  '/sculpting': typeof SculptingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/subscription': typeof SubscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acrobatics'
    | '/contact'
    | '/dance'
    | '/faq'
    | '/gallery'
    | '/music'
    | '/paintings'
    | '/sculpting'
    | '/sitemap.xml'
    | '/studio'
    | '/subscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acrobatics'
    | '/contact'
    | '/dance'
    | '/faq'
    | '/gallery'
    | '/music'
    | '/paintings'
    | '/sculpting'
    | '/sitemap.xml'
    | '/studio'
    | '/subscription'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/acrobatics'
    | '/contact'
    | '/dance'
    | '/faq'
    | '/gallery'
    | '/music'
    | '/paintings'
    | '/sculpting'
    | '/sitemap.xml'
    | '/studio'
    | '/subscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcrobaticsRoute: typeof AcrobaticsRoute
  ContactRoute: typeof ContactRoute
  DanceRoute: typeof DanceRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  MusicRoute: typeof MusicRoute
  PaintingsRoute: typeof PaintingsRoute
  SculptingRoute: typeof SculptingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  SubscriptionRoute: typeof SubscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acrobatics': {
      id: '/acrobatics'
      path: '/acrobatics'
      fullPath: '/acrobatics'
      preLoaderRoute: typeof AcrobaticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dance': {
      id: '/dance'
      path: '/dance'
      fullPath: '/dance'
      preLoaderRoute: typeof DanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paintings': {
      id: '/paintings'
      path: '/paintings'
      fullPath: '/paintings'
      preLoaderRoute: typeof PaintingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sculpting': {
      id: '/sculpting'
      path: '/sculpting'
      fullPath: '/sculpting'
      preLoaderRoute: typeof SculptingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcrobaticsRoute: AcrobaticsRoute,
  ContactRoute: ContactRoute,
  DanceRoute: DanceRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  MusicRoute: MusicRoute,
  PaintingsRoute: PaintingsRoute,
  SculptingRoute: SculptingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  SubscriptionRoute: SubscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
